name: build-publish-client
on:
   workflow_dispatch:
   push:
     branches:
       - master
     tags:
       - 'v*'  
     paths:
       - 'client/**'
defaults:
  run:
    working-directory: client
jobs:
  build-it:
    runs-on: ubuntu-latest
    steps:
#     - name: Get latest tag
#       id: vars
#       run: echo ::set-output name=tag::${GITHUB_REF:10}

     - name: Clone repository
       uses: actions/checkout@v2
       with:
         ref: ${{ steps.vars.outputs.tag }}

     - name: Set up QEMU
       uses: docker/setup-qemu-action@v2
       with:
          image: tonistiigi/binfmt:latest
          platforms: arm64,arm

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

    #  - name: Login to ghcr.io
    #    uses: docker/login-action@v2
    #    with:
    #       registry: ghcr.io
    #       username: ${{ github.actor }}
    #       password: ${{ secrets.GITHUB_TOKEN }}

     - name: 'Login to GitHub Container Registry'
       uses: docker/login
       run: |
          echo $GHCR_TOKEN | docker login ghcr.io -u davideshay --password-stdin          

     - name: Docker meta
       id: meta
       uses: docker/metadata-action@v4
       with:
          images: |
            name/app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

     - name: Build and push
       uses: docker/build-push-action@v4
       with:
#          context: "{{defaultContext}}:client"
          file: client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
#          tags: ghcr.io/${{ GITHUB.REPOSITORY }}client:latest
#          tags: ${{ steps.meta.outputs.tags }}-client
          tags: ghcr.io/${{ steps.meta.outputs.tags }}-client
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max